# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20180618_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='public_certificate',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
